Controllers/ClientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoGestor.Data;
using ProyectoGestor.Models;
using ProyectoGestor.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoGestor.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        private readonly AppDbContext _context;

        public ClientsController(AppDbContext context)
        {
            _context = context;
        }

        /*public async Task<IActionResult> Index()
        {
            var context = _context.Clients.Include(c => c.Locality);
            return View(await context.ToListAsync());
        }*/

        public async Task<IActionResult> Index(string sortOrdenation, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrdenation;
            ViewData["LastNameSortParm"] = String.IsNullOrEmpty(sortOrdenation) ? "LastName_desc" : "";
            ViewData["NameSortParm"] = sortOrdenation == "Name" ? "Name_desc" : "Name";
            ViewData["EmailSortParm"] = sortOrdenation == "Email" ? "Email_desc" : "Email";
            ViewData["PhoneNumberSortParm"] = sortOrdenation == "PhoneNumber" ? "PhoneNumber_desc" : "PhoneNumber";
            ViewData["CIFSortParm"] = sortOrdenation == "CIF" ? "CIF_desc" : "CIF";
            ViewData["AddressSortParm"] = sortOrdenation == "Address" ? "Address_desc" : "Address";
            ViewData["LocalityIDSortParm"] = sortOrdenation == "LocalityID" ? "LocalityID_desc" : "LocalityID";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var clients = from c in _context.Clients.Include(i => i.Locality)
                          select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(s => s.LastName.Contains(searchString)
                                       || s.Name.Contains(searchString));
            }
            switch (sortOrdenation)
            {
                case "LastName_desc":
                    clients = clients.OrderByDescending(s => s.LastName);
                    break;
                case "Name":
                    clients = clients.OrderBy(c => c.Name);
                    break;
                case "Name_desc":
                    clients = clients.OrderByDescending(c => c.Name);
                    break;
                case "Email":
                    clients = clients.OrderBy(c => c.Email);
                    break;
                case "Email_desc":
                    clients = clients.OrderByDescending(c => c.Email);
                    break;
                case "PhoneNumber":
                    clients = clients.OrderBy(c => c.PhoneNumber);
                    break;
                case "PhoneNumber_desc":
                    clients = clients.OrderByDescending(c => c.PhoneNumber);
                    break;
                case "CIF":
                    clients = clients.OrderBy(c => c.CIF);
                    break;
                case "CIF_desc":
                    clients = clients.OrderByDescending(c => c.CIF);
                    break;
                case "Address":
                    clients = clients.OrderBy(c => c.Address);
                    break;
                case "Address_desc":
                    clients = clients.OrderByDescending(c => c.Address);
                    break;
                case "LocalityID":
                    clients = clients.OrderBy(c => c.Locality.Name);
                    break;
                case "LocalityID_desc":
                    clients = clients.OrderByDescending(c => c.Locality.Name);
                    break;
                default:
                    clients = clients.OrderBy(s => s.LastName);
                    break;
            }
            int pageSize = 5;
            return View(await PaginatedList<Client>.CreateAsync(clients.AsNoTracking(), pageNumber ?? 1, pageSize));
            //return View(await clients.AsNoTracking().ToListAsync());
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,LastName,Email,PhoneNumber,CIF,Address,LocalityID")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalityID"] = new SelectList(_context.Localities, "ID", "ID", client.LocalityID);
            //PopulateLocalitiesDropDownList(client.LocalityID);
            return View(client);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var client = await _context.Clients.FindAsync(id);
            var client = await _context.Clients
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (client == null)
            {
                return NotFound();
            }
            ViewData["LocalityID"] = new SelectList(_context.Localities, "ID", "ID", client.LocalityID);
            //PopulateLocalitiesDropDownList(client.LocalityID);
            return View(client);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,LastName,Email,PhoneNumber,CIF,Address,LocalityID")] Client client)
        {
            if (id != client.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalityID"] = new SelectList(_context.Localities, "ID", "ID", client.LocalityID);
            //PopulateLocalitiesDropDownList(client.LocalityID);
            return View(client);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.Locality)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.ID == id);
        }

    }
}

Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoGestor.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoGestor.Controllers
{
    [Authorize]
    public class InvoicesController : Controller
    {
        private readonly AppDbContext _context;

        public InvoicesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var context = _context.Invoices.Include(i => i.Order);
            return View(await context.ToListAsync());
        }
    }
}

Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoGestor.Data;
using ProyectoGestor.Models;
using ProyectoGestor.Models.OrderProductViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProyectoGestor.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly AppDbContext _context;

        public OrdersController(AppDbContext context)
        {
            _context = context;
        }

        /*public async Task<IActionResult> Index()
        {
            //var context = _context.Orders.Include(o => o.Client).Include(o => o.ProductID);
            // View(await context.ToListAsync());
            
        }*/
        public async Task<IActionResult> Index(int? id, int? productID)
        {
            var viewModel = new OrderIndexData();
            viewModel.Orders = await _context.Orders
                  .Include(i => i.OrderProduct)
                    .ThenInclude(i => i.Product)
                        .ThenInclude(i => i.ProductCategory)
                  .Include(i => i.Client)
                  .AsNoTracking()
                  .ToListAsync();

            if (id != null)
            {
                ViewData["OrderID"] = id.Value;
                Order order = viewModel.Orders.Where(
                    i => i.OrderID == id.Value).Single();
                viewModel.Products = order.OrderProduct.Select(s => s.Product);
            }
            return View(viewModel);
        }

        public IActionResult Create()
        {
            var order = new Order();
            order.OrderProduct = new List<OrderProduct>();
            ViewData["ClientID"] = new SelectList(_context.Clients, "ID", "ID");
            PopulateAssignedProductData(order);
            return View();
        }

        // POST: Instructors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderID,Date,ClientID,ProductOrder")] Order order, string[] selectedProducts)
        {
            if (selectedProducts != null)
            {
                order.OrderProduct = new List<OrderProduct>();
                foreach (var product in selectedProducts)
                {
                    var productToAdd = new OrderProduct { OrderID = order.OrderID, ProductID = int.Parse(product) };
                    order.OrderProduct.Add(productToAdd);
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            PopulateAssignedProductData(order);
            return View(order);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(i => i.OrderProduct)
                .ThenInclude(i => i.Product)
                .Include(i => i.Client)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }
            //idea 
            ViewData["ClientID"] = new SelectList(_context.Clients, "ID", "ID", order.ClientID);

            PopulateAssignedProductData(order);
            return View(order);
        }

        private void PopulateAssignedProductData(Order order)
        {
            var allProducts = _context.Products;
            var orderProducts = new HashSet<int>(order.OrderProduct.Select(c => c.ProductID));
            var viewModel = new List<AssignedProductData>();
            foreach (var product in allProducts)
            {
                viewModel.Add(new AssignedProductData
                {
                    ID = product.ID,
                    Name = product.Name,
                    Assigned = orderProducts.Contains(product.ID)
                });
            }
            ViewData["Products"] = viewModel;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, string[] selectedProducts)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderToUpdate = await _context.Orders
                .Include(i => i.Client)
                .Include(i => i.OrderProduct)
                    .ThenInclude(i => i.Product)
                .FirstOrDefaultAsync(m => m.OrderID == id);

            if (await TryUpdateModelAsync<Order>(
                orderToUpdate,
                "",
                i => i.OrderID, i => i.Date, i => i.ClientID))
            {
                UpdateOrderProducts(selectedProducts, orderToUpdate);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
                return RedirectToAction(nameof(Index));
            }
            UpdateOrderProducts(selectedProducts, orderToUpdate);
            PopulateAssignedProductData(orderToUpdate);
            return View(orderToUpdate);
        }

        private void UpdateOrderProducts(string[] selectedProducts, Order orderToUpdate)
        {
            if (selectedProducts == null)
            {
                orderToUpdate.OrderProduct = new List<OrderProduct>();
                return;
            }

            var selectedProductsHS = new HashSet<string>(selectedProducts);
            var orderProducts = new HashSet<int>
                (orderToUpdate.OrderProduct.Select(c => c.Product.ID));
            foreach (var product in _context.Products)
            {
                if (selectedProductsHS.Contains(product.ID.ToString()))
                {
                    if (!orderProducts.Contains(product.ID))
                    {
                        orderToUpdate.OrderProduct.Add(new OrderProduct { OrderID = orderToUpdate.OrderID, ProductID = product.ID });
                    }
                }
                else
                {

                    if (orderProducts.Contains(product.ID))
                    {
                        OrderProduct productToRemove = orderToUpdate.OrderProduct.FirstOrDefault(i => i.ProductID == product.ID);
                        _context.Remove(productToRemove);
                    }
                }
            }
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Client)
                .FirstOrDefaultAsync(m => m.OrderID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                Order order = await _context.Orders
                    .Include(i => i.OrderProduct)
                    .Include(i => i.Client)
                    .SingleAsync(i => i.OrderID == id);

                _context.Orders.Remove(order);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message + " No se pueden borrar pedidos con productos dentro.";
                return View("NotFound");
            }

        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderID == id);
        }
    }
}

Controllers/ProvincesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoGestor.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace ProyectoGestor.Controllers
{
    [Authorize]
    public class ProvincesController : Controller
    {
        private readonly AppDbContext _context;
        public ProvincesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Provinces.ToListAsync());
        }
    }
}

Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Pincha aqui para volver a la página principal
</a>

Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoGestor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script href="~/lib/jquery/dist/jquery.js"></script>
    <script href="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script href="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script href="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <!--Font awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoGestor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Clients" asp-action="index">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Products" asp-action="index">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Orders" asp-action="index">Pedidos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Invoices" asp-action="index">Facturas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Localities" asp-action="index">Localidades</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Provinces" asp-action="index">Provincias</a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Gestión
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListUsers">Usuarios</a>
                                    <a class="dropdown-item" asp-controller="Administration"
                                       asp-action="ListRoles">Roles</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @*If the user is signed-in display Logout link*@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-controller="account" asp-action="logout">
                                    <button type="submit" style="width:auto"
                                            class="nav-link btn btn-link py-0">
                                        Cerrar sesión de @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="register">
                                    Registro
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="login">
                                    Inicio sesión
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProyectoGestor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--RenderSection("Scripts", required: false)-->
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true)
    }
</body>
</html>